[tool.black]
line-length = 100
target-version = ["py312"]
extend-exclude = """
^\\.venv/
"""

[tool.isort]
profile = "black"
line_length = 100
src_paths = ["backend"]
skip = [".venv"]

[tool.ruff]
line-length = 100
target-version = "py312"
src = ["backend"]
extend-exclude = [".venv"]

[tool.ruff.lint]
# mueve aqu√≠ lo que hoy tienes como "ignore" y "select"
ignore = []
select = ["E", "F", "I", "UP", "B", "SIM", "PIE"]
extend-select = ["I"]

[tool.ruff.format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false
line-ending = "lf"
